# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

group=com.github.sebseb7
mod_id=autotrade
mod_name=AutoTrade
mod_group=com.github.sebseb7.autotrade
author=sebseb7
mod_file_name=autotrade-fabric

mod_version=0.0.14
