name: Build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: modrinth
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Execute Gradle build
      run: ./gradlew build
    - run: mkdir staging && cp build/libs/*.jar staging
    - run: cd build/libs && md5sum *.jar > ../../md5sum.txt
    - run: echo "filename=`ls build/libs/*.jar |xargs basename`" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.filename }}
        path: staging
    - uses: actions/upload-artifact@v3
      with:
        name: md5sum.txt
        path: md5sum.txt
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/libs/*.jar
    - name: Modrinth Readme Sync
      env:
         MODRINTH_TOKEN: ${{ vars.MODRINTH_TOKEN }}
      run: ./gradlew modrinthSyncBody
    - name: Modrinth Release
      if: startsWith(github.ref, 'refs/tags/')
      env:
         MODRINTH_TOKEN: ${{ vars.MODRINTH_TOKEN }}
      run: ./gradlew modrinth
